// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxbqtxfmcdpiplsaepag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4YnF0eGZtY2RwaXBsc2FlcGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NDI0MDgsImV4cCI6MjA2MjMxODQwOH0.-18HRKvTDoKMIohfqj8PmFqfyBMbDnXh5JG_Yn3Bf4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);